name: Tests

on: workflow_call

env:
  PYTHON_VERSION: '3.10'

jobs:
  setup:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipenv
          pipenv install
      - name: Test with pytest
        run: |
          pipenv run pytest --cov --cov-report=xml