name: Tests

on:
  workflow_call:
    inputs:
      cache_key:
        description: 'Cache key for coverage report'
        required: false
        type: string

env:
  PYTHON_VERSION: '3.10'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipenv
          pipenv install
      - name: Test with pytest
        run: |
          pipenv run pytest --cov --cov-report=xml
      - name: Cache coverage report
        uses: actions/cache@v4
        with:
          path: coverage.xml
          key: ${{inputs.cache_key}}